Try to run reveng from the 'quarkus dev cli'   - Make password optional in configuration   - Fails with a 'NoSuchMethodError' -> HT needs to be updated
Signed-off-by: Koen Aers <koen.aers@gmail.com>